server:
  port: 8180

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    password: jenskohler
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
    format_sql: true
    show-sql: true


#Postgres Config
#spring:
#  datasource:
#    username: root
#    url: jdbc:postgresql://localhost:5432/demo
#    password: jenskohler
#    initialize: true
#    initialization-mode: always
#  jpa.hibernate:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    format_sql: 'true'
#    ddl-auto: create-drop
#    show-sql: 'true'

# This secret key is combined with the header and the payload to create a unique hash.
# We are only able to verify this hash if you have the secret key.
jwt:
  secret: jenskohler
  expiration: 86400000