apiVersion: v1
kind: Service
metadata:
  name: auth-service-mariadb
  labels:
    app: auth
spec:
  type: {{ .Values.mariadbService.service.type }}
  ports:
    - port: {{ .Values.mariadbService.service.port }}
      targetPort: {{ .Values.mariadbService.service.port }}
      protocol: TCP
      name: mariadb
  selector:
    app: mariadb
