apiVersion: v1
kind: Service
metadata:
  name: auth-service-postgresql
  labels:
    app: postgres
spec:
  type: {{ .Values.postgresqlService.service.type }}
  ports:
    - port: {{ .Values.postgresqlService.service.port }}
      targetPort: {{ .Values.postgresqlService.service.port }}
      protocol: TCP
      name: postgres
  selector:
      app: postgres
