apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.customerService.autoscaling.enabled }}
  replicas: {{ .Values.customerService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.customerService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.customerService.image.repository }}:{{ .Values.customerService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.customerService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.customerService.resources | nindent 12 }}

