spring:
  datasource:
    username: root
    url: jdbc:mysql://mariadb.default.svc.cluster.local:3306/demo?useSSL=false
    password: jenskohler
  jpa:
    properties:
  hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    format_sql: 'true'
    ddl-auto: create-drop
    show-sql: 'true'
