spring:
  datasource:
    username: root
    url: jdbc:mysql://customer-service-mariadb:3306/demo?useSSL=false
    password: jenskohler
  jpa.hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    format_sql: 'true'
    ddl-auto: create-drop
    show-sql: 'true'
