## order Service
orderService:
  replicaCount: 1
  image:
    repository: order-service
    #Always does not work for minikube (error pulling image), so we just use the latest tag
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 8080
    protocol: TCP
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      memory: 2Gi
      cpu: "1"

## PostgreSQL Database Service
postgresqlService:
  replicaCount: 1
  image:
    repository: order-service-db-postgres
    #Always does not work for minikube (error pulling image), so we just use the latest tag
    #pullPolicy: Always
    tag: "latest"
  service:
    type: NodePort
    port: 5432
    protocol: TCP
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      memory: 2Gi
      cpu: "1"

## MariaDB Database Service
mariadbService:
  service:
    type: NodePort
    port: 3306
    protocol: TCP