apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-postgresql
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: {{ .Values.postgresqlService.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: demo
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: jenskohler
          resources:
            {{- toYaml .Values.postgresqlService.resources | nindent 12 }}
  replicas: {{ .Values.postgresqlService.replicaCount }}